########
##APPS##
########
##$screenshot = env XDG_CURRENT_DESKTOP=Sway flameshot gui
##$entire_screenshot = env XDG_CURRENT_DESKTOP=Sway flameshot full
$browser = firefox
$browser2 = /usr/bin/google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland
#$launcher = rofi -show drun -theme ~/.config/rofi/hoc2.rasi
#$launcher2 = rofi -show drun -config ~/.config/rofi/themes/launch.rasi
$launcher3 = elysia-launcher
$texteditor = code
$discord = XDG_CURRENT_DESKTOP=Hyprland vesktop
$filemanager = thunar
$terminal = kitty
$screenshot_region = ~/.config/hypr/Scripts/screenshot-region.sh
$screenshot_screen = ~/.config/hypr/Scripts/screenshot-full.sh
$ely-widget-stats = elysia-widget-daemon --stats
$wallpaper-menu = ~/.config/rofi/scripts/rofi-wallpaper.sh
$elysia-tab = ely-workspace
$ely-widget = elysia-widget-daemon
$ely-notify = elysia-widget-daemon --notif

